# -*- coding: utf-8 -*-
"""Boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rx22-CU5UZUxmQRN86pJJgybEpxC8EFx
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Put dataset on my github repo
df = pd.read_csv('https://raw.githubusercontent.com/mGalarnyk/Python_Tutorials/master/Kaggle/BreastCancerWisconsin/data/data.csv')

sns.boxplot(x='diagnosis', y='area_mean', data=df)

malignant = df[df['diagnosis']=='M']['area_mean']
benign = df[df['diagnosis']=='B']['area_mean']

fig = plt.figure()
ax = fig.add_subplot(111)
ax.boxplot([malignant,benign], labels=['M', 'B'])

df.boxplot(column = 'area_mean', by = 'diagnosis');
plt.title('')

malignant = df[df['diagnosis']=='M']['area_mean']
benign = df[df['diagnosis']=='B']['area_mean']

fig = plt.figure()
ax = fig.add_subplot(111)
ax.boxplot([malignant,benign], notch = False, labels=['M', 'B']);